In [1]:
# common
import numpy as np

**Create Array**
- array
- asarray (convert input to ndarray)
- arange
- ones, ones_like
- zeros, zeros_like
- empty, empty_like
- full, full_like
- eye, identity (create N x N identity matrix)

In [2]:
data = np.array([[1.5, -0.1, 3], [0, 1, 2]])

In [5]:
print("shape", data.shape, "dtype",data.dtype, "ndim", data.ndim)

shape (2, 3) dtype float64 ndim 2


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones_like((2, 4), dtype='int64')

array([1, 1], dtype=int64)

In [ ]:
# empty creates without initialization
np.empty((2,3))

array([[3.47739925e-081, 2.04081507e+184, 5.11081339e-066],
       [9.40855110e-047, 8.97772319e-067, 1.05699581e-307]])

In [10]:
np.full((2, 4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

### Data types
- int8, uint8, int16, uint16, int32, uint32, int64, uint64
- float16(f2), float32(f4 or f), float64(f8 or d), float128(f16 or g)
- complex64, complex128, complex256
- bool(?), object(0)
- string_(S) (fixed-length ASCII string type, 1 byte per char)
- unicode_(U) (Fiexed-length Unicode type)

In [13]:
arr = np.arange(5)

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr.astype(np.float64)

array([0., 1., 2., 3., 4.])

In [18]:
arr = np.array(["1.25", "40"], dtype=np.string_)

In [19]:
arr.astype(float)

array([ 1.25, 40.  ])

### Arithmetic

In [23]:
arr = np.array([[1,2,3], [4,5,6]])
# equal-size arrays apply the operation element-wise
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [25]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

### Slice Assignment

In [33]:
arr = np.arange(10)

In [34]:
arr_slice = arr[2:4]

In [35]:
arr_slice[:] = 100
arr

array([  0,   1, 100, 100,   4,   5,   6,   7,   8,   9])

In [36]:
copy_slice = arr[2:4].copy()

In [37]:
copy_slice[:] = 200
arr

array([  0,   1, 100, 100,   4,   5,   6,   7,   8,   9])

### Accessing to array

In [39]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[1][1], arr[1, 1])

5 5


In [40]:
arr[0]

array([1, 2, 3])

In [41]:
arr[:2, :2]

array([[1, 2],
       [4, 5]])

### Boolean Indexing

In [45]:
names = np.array(['Jason', 'Bill', 'Trump', 'Bill'])
data = np.array([1, 2, 3, 4])
names

array(['Jason', 'Bill', 'Trump', 'Bill'], dtype='<U5')

In [46]:
names == 'Bill'

array([False,  True, False,  True])

In [47]:
data[names == 'Bill']

array([2, 4])

In [50]:
data[names == 'Bill'] = 0
data

array([1, 0, 3, 0])

In [52]:
data[~(names == 'Bill')] = 10
data

array([10,  0, 10,  0])

In [56]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

### Reshape

In [61]:
data = data.reshape((2,3))
data[data < 3]

array([0, 1, 2])

In [ ]:
data[[1, 0]]

array([[3, 4, 5],
       [0, 1, 2]])

### Transposing Array and Swapping Axes

In [67]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
np.dot(arr, arr.T)

array([[ 5, 14],
       [14, 50]])

In [69]:
arr @ arr.T

array([[ 5, 14],
       [14, 50]])

In [70]:
arr.swapaxes(0, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

### random number generation
generator methods
- permutation
- shuffle
- uniform
- integers
- standard_normal
- binomial
- normal
- beta
- chisquare
- gamma
- uniform

In [71]:
# from normal distribution
np.random.standard_normal(size=(2,2))

array([[-1.13888415,  0.98066272],
       [-0.16473814,  0.21542611]])

In [72]:
from random import normalvariate
N = 1_000_000

In [73]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

382 ms ± 20.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%timeit np.random.standard_normal(N)

15.1 ms ± 498 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Universal Functions
Unary
- abs, fabs
- sqrt
- square
- exp
- log, log10, log2, log1p
- sign
- ceil, floor
- rint, modf
- isnan, isfinite, isinf
- cos, cosh, sin, sinh, tan, tanh
- arccos, arccosh, arcsin, arcsinh, arctan, arctanh
- logical_not
Binary
- add, subtract, multiply, divider, power
- maximum, fmax, minimum, fmin
- mod, copysign, greater, greater_equal, less, less_euql, equal
- logical_and
- logical_or
- logical_xor

In [77]:
arr = np.random.standard_normal(10)
arr1 = np.random.standard_normal(10)

In [78]:
arr

array([ 0.0627633 , -0.55168796, -0.75433981,  1.6064708 ,  0.02716324,
        0.03334546,  0.11234778,  1.02064444, -0.00910874,  0.3652805 ])

In [79]:
arr1

array([ 1.54827025, -1.09180447, -0.92152384,  0.02344993, -0.05759868,
       -1.2108182 ,  0.73133322,  0.18912439, -1.36373125, -0.87768356])

In [80]:
np.maximum(arr, arr1)

array([ 1.54827025, -0.55168796, -0.75433981,  1.6064708 ,  0.02716324,
        0.03334546,  0.73133322,  1.02064444, -0.00910874,  0.3652805 ])

### Conditional Logic

In [81]:
arr = np.arange(10)
arr1 = arr[:5]
arr2 = arr[5:]

In [82]:
cond = np.array([True, False, False, False, True])
np.where(cond, arr1, arr2)

array([0, 6, 7, 8, 4])

In [84]:
np.where(arr1 > 2, 1, -1)

array([-1, -1, -1,  1,  1])

### Mathematics, Statistics
- sum, mean, std, var, min, max, argmin, argmax, cumsum, cumprod

### Sorting, Array set
Array set
- unique
- intersection
- union1d
- in1d
- setdiff1d
- setxor1d

In [85]:
arr = np.arange(5, -5, -1)

In [91]:
arr = arr.reshape((5, 2))
arr

array([[ 5,  4],
       [ 3,  2],
       [ 1,  0],
       [-1, -2],
       [-3, -4]])

In [94]:
arr.sort(axis=1)
arr

array([[ 4,  5],
       [ 2,  3],
       [ 0,  1],
       [-2, -1],
       [-4, -3]])

In [97]:
arr = np.array(['aaa', 'aab', 'aab', 'aaa'])
np.unique(arr)

array(['aaa', 'aab'], dtype='<U3')

### File Input / Ouput
`np.save("arr.npy", arr)`

`np.load("arr.npy")`

### Linear Algebra
- diag
- dot
- trace
- det
- eig
- inv
- pinv
- qr
- svd
- solve
- lstsq