$$
2x - y = 0 \\
-x + 2y - z = -1 \\
-3y + 4z = 4
$$ 

Row picture, 3 different planes
$$
A=\begin{bmatrix*}[r]
2&-1&0\\
-1&2&-1\\
0&-3&4
\end{bmatrix*}
\,,
b = 
\begin{bmatrix*}[r]
0\\-1\\4
\end{bmatrix*}
$$

Column picture (Linear Combination of columns)
$$
x
\begin{bmatrix*}[r]
2\\-1\\0
\end{bmatrix*} +
y
\begin{bmatrix*}[r]
-1\\2\\-3
\end{bmatrix*} +
z
\begin{bmatrix*}[r]
0\\-1\\4
\end{bmatrix*}
=
\begin{bmatrix*}[r]
0\\-1\\4
\end{bmatrix*}
$$

- Can I solve Ax=b for every b?
- Do the linear combs of the columns fill 3-D space?

### Elinimation
$$
\begin{cases}
Success \\
Fail
\end{cases}
$$

$$
x+2y+z=2 \\
3x+8y+z=12 \\
4y+z=2
$$

$$
A=\begin{bmatrix*}[r]
1(first pivot)&2&1\\
3&8&1\\
0&4&1
\end{bmatrix*}
\;
\rightarrow \begin{bmatrix*}[r]
1&2&1\\
0&2(second pivot)&-2\\
0&4&1
\end{bmatrix*}
\;
\rightarrow \begin{bmatrix*}[r]
1&2&1\\
0&2&-2\\
0&0&5
\end{bmatrix*}
$$
- U = Upper Triangle
- How could be failed? - if get 0 pivot -> row exchange
- when second pivot is zero -> also can switch with another row which second pivot is not zero

In [ ]:
import numpy as np
A = np.array([[1, 2, 1, 2], [3, 8, 1, 12], [0, 4, 1, 2]])
A[1, :] = A[1, :] - 3 * A[0, :]
print(A)
A[2, :] -= 2 * A[1, :]
print(A)
# 5z = -10 -> z = -2 and go reverse steps to find x, y

[[ 1  2  1  2]
 [ 0  2 -2  6]
 [ 0  4  1  2]]
[[  1   2   1   2]
 [  0   2  -2   6]
 [  0   0   5 -10]]


In [ ]:
# fail case, third row become all zeros
A = np.array([[1, 2, 1], [3, 8, 1], [0, 4, -4]])
A[1, :] = A[1, :] - 3 * A[0, :]
A[2, :] -= 2 * A[1, :]
print(A)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  0  0]]
